# Generated by Django 3.0.8 on 2020-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=300)),
                ('amazon_link', models.URLField(blank=True, max_length=300, null=True)),
                ('other_link', models.URLField(blank=True, max_length=300, null=True)),
                ('other_link1', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('other_image', models.URLField(max_length=300)),
                ('other_image1', models.URLField(max_length=300)),
            ],
            options={
                'ordering': ['title', 'brand'],
            },
        ),
    ]
