# Generated by Django 3.0.8 on 2020-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_about_us_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='facebook_page2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
