# Generated by Django 3.0.8 on 2020-09-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_about_us_facebook_page2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'ordering': ['title'], 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name_plural': 'Services'},
        ),
    ]
