# Generated by Django 3.0.8 on 2020-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200917_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='description')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
