# Generated by Django 3.0.8 on 2020-09-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_about_us_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_link1',
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
