# Generated by Django 3.0.8 on 2020-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200919_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image url')),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('send_date', models.DateTimeField(auto_now=True, verbose_name='send date')),
            ],
        ),
    ]
