# Generated by Django 3.0.8 on 2020-09-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_contact_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['country', 'phone_number']},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['name'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='product',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='other_image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='other_image1',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
